trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '20.10.7'

  - script: |
      echo "Downloading Kaniko executor..."
      curl -L https://github.com/GoogleContainerTools/kaniko/releases/latest/download/executor -o executor
      chmod +x executor
      ls -lah executor
    displayName: 'Install Kaniko'

  - script: |
      ./executor \
        --context https://github.com/your-username/kaniko-test.git \
        --dockerfile Dockerfile \
        --destination kanikotestacr.azurecr.io/kaniko-test:latest \
        --skip-tls-verify
    env:
      DOCKER_CONFIG: /kaniko/.docker/
    displayName: 'Build and Push Image Using Kaniko'
