trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '20.10.7'

  - script: |
      echo "Installing Kaniko..."
      curl -LO https://github.com/GoogleContainerTools/kaniko/releases/latest/download/executor
      chmod +x executor
    displayName: 'Install Kaniko'

  - script: |
      ./executor \
        --context https://github.com/Dhanush1219/kaniko-test.git \
        --dockerfile Dockerfile \
        --destination hardikpoc.azurecr.io/kaniko-test:latest \
        --skip-tls-verify
    env:
      DOCKER_CONFIG: /kaniko/.docker/
    displayName: 'Build and Push Image Using Kaniko'
